import duckling
d = duckling.Duckling()
d.load()
print(d.parse("tomorrow"))
print(d.parse("daniel@fartbox.com"))
print(d.parse("daniel at fartbox dot com"))
print(d.parse("daniel that fartbox dot com"))
print(d.parse("daniel at fartbox dot org"))
print(d.parse("daniel at fartbox dot info"))
print(d.parse("daniel at fartbox dot gov"))
